name: CI/CD

on: push

jobs:
    build: # Always build and check linters and style pass
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
            - name: Install modules
              run: npm ci
            - name: Run ESLint
              run: npm run lint
            - name: Run type
              run: npm run type
            - name: Build
              run: npm run build --if-present

    # Deploy if push to main
    deploy:
        permissions:
            contents: write

        runs-on: ubuntu-latest

        # Ensure Build Passes
        needs: build

        # Verify PR to Main
        if: github.ref == 'refs/heads/main'

        # Build and then deploy page
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
            - name: Install modules
              run: npm ci
            - name: Deploy with gh-pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
